# Generated by Django 5.1.6 on 2026-02-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_CRUD', '0002_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='S_CRUD.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_CRUD.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
