# Generated by Django 5.1.6 on 2026-02-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_CRUD.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, to='S_CRUD.course')),
                ('subjects', models.ManyToManyField(blank=True, to='S_CRUD.subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='S_CRUD.subject'),
        ),
        migrations.CreateModel(
            name='BatchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_subjects', to='S_CRUD.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_CRUD.subject')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='subjects',
            field=models.ManyToManyField(related_name='batches', through='S_CRUD.BatchSubject', to='S_CRUD.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('subjects', models.ManyToManyField(blank=True, to='S_CRUD.subject')),
            ],
        ),
        migrations.AddField(
            model_name='batchsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_CRUD.teacher'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(related_name='batches', through='S_CRUD.BatchSubject', to='S_CRUD.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='batchsubject',
            unique_together={('batch', 'subject')},
        ),
    ]
